//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramadeEncuestas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DW_ENCUESTAS
    {
        public int ID_ENCUESTA { get; set; }
        public int ID_IDIOMA { get; set; }
        public int ID_ESTADO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string PERIODO { get; set; }
        public string USUARIO_C { get; set; }
        public string USUARIO_M { get; set; }
        public Nullable<System.DateTime> FECHA_C { get; set; }
        public Nullable<System.DateTime> FECHA_M { get; set; }
    }
}
