//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramadeEncuestas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WEB_PERSONAL_CAMPO
    {
        public int ID_PERSONAL { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CEDULA { get; set; }
        public string PROVINCIA { get; set; }
        public string CARGO { get; set; }
        public string ESTADO { get; set; }
        public string ENCUESTA { get; set; }
        public string TELEFONO1 { get; set; }
        public string TELEFONO2 { get; set; }
        public string FOTO { get; set; }
    }
}
